//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuMuon
    {
        public int ID { get; set; }
        public int MaPhieuMuon { get; set; }
        public int MaCuonSach { get; set; }
    
        public virtual CuonSach CuonSach { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
    }
}
