//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuonSach
    {
        public CuonSach()
        {
            this.CTPhieuMuon = new HashSet<CTPhieuMuon>();
            this.CTPhieuTra = new HashSet<CTPhieuTra>();
        }
    
        public int MaCuonSach { get; set; }
        public Nullable<int> MaDauSach { get; set; }
        public Nullable<int> MaTinhTrang { get; set; }
    
        public virtual ICollection<CTPhieuMuon> CTPhieuMuon { get; set; }
        public virtual ICollection<CTPhieuTra> CTPhieuTra { get; set; }
        public virtual DauSach DauSach { get; set; }
        public virtual TinhTrangCuonSach TinhTrangCuonSach { get; set; }
    }
}
