//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DauSach
    {
        public DauSach()
        {
            this.CuonSach = new HashSet<CuonSach>();
        }
    
        public int MaDauSach { get; set; }
        public Nullable<int> MaLoai { get; set; }
        public string TenDauSach { get; set; }
        public Nullable<int> MaNXB { get; set; }
        public Nullable<int> MaTrangThai { get; set; }
        public string TomTat { get; set; }
        public Nullable<int> MaTacGia { get; set; }
    
        public virtual ICollection<CuonSach> CuonSach { get; set; }
        public virtual LoaiSach LoaiSach { get; set; }
        public virtual NXB NXB { get; set; }
        public virtual TrangThaiDauSach TrangThaiDauSach { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
