//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLThuVienEntities : DbContext
    {
        public QLThuVienEntities()
            : base("name=QLThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CTPhieuMuon> CTPhieuMuon { get; set; }
        public DbSet<CTPhieuTra> CTPhieuTra { get; set; }
        public DbSet<CuonSach> CuonSach { get; set; }
        public DbSet<DauSach> DauSach { get; set; }
        public DbSet<DocGia> DocGia { get; set; }
        public DbSet<LoaiSach> LoaiSach { get; set; }
        public DbSet<NXB> NXB { get; set; }
        public DbSet<PhieuMuon> PhieuMuon { get; set; }
        public DbSet<PhieuTra> PhieuTra { get; set; }
        public DbSet<TacGia> TacGia { get; set; }
        public DbSet<TinhTrangCuonSach> TinhTrangCuonSach { get; set; }
        public DbSet<TrangThaiDauSach> TrangThaiDauSach { get; set; }
    }
}
