//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocGia
    {
        public DocGia()
        {
            this.PhieuMuon = new HashSet<PhieuMuon>();
        }
    
        public int MaDocGia { get; set; }
        public string TenDocGia { get; set; }
        public Nullable<bool> VienChuc { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> NamTotNgiep { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
    
        public virtual ICollection<PhieuMuon> PhieuMuon { get; set; }
    }
}
