//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia
    {
        public TacGia()
        {
            this.TacGia_Sach = new HashSet<TacGia_Sach>();
        }
    
        public int MaTacGia { get; set; }
        public string TenTacGia { get; set; }
        public string NoiCongTac { get; set; }
    
        public virtual ICollection<TacGia_Sach> TacGia_Sach { get; set; }
    }
}
