//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacGia_Sach
    {
        public int ID { get; set; }
        public int MaDauSach { get; set; }
        public int MaTacGia { get; set; }
    
        public virtual DauSach DauSach { get; set; }
        public virtual TacGia TacGia { get; set; }
    }
}
